### ISSUE TITLE
Issue creating a file

### ISSUE THREAD

**Issue by JaviBonilla** [appwrite/sdk-for-python#31]
When creating a file with the following code using a JWT

```python

# Token info
token_data = jwt.decode(token, server.SECRET_KEY, algorithms=server.ALGORITHM)
print(f'JWT:  {token}')
print(f'JWT: {token_data}')

# Client
client = Client().set_endpoint(ENDPOINT).set_project(PROJECT).set_jwt(token)

# Making sure token is ok
account = Account(client)
print(account.get())

# Creating a new file
storage = Storage(client)
res = storage.create_file(open('image.png', 'rb'))
```

The following error is thrown
```
[Error] Method: POST
[Error] URL: /v1/storage/files
[Error] Type: Appwrite\Database\Exception\Authorization
[Error] Message: Missing "write" permission for role "user:60bf4dfc2c7f4". Only this scopes "["*"]" are given and only this are allowed "["user:60bf4dfc2c7f4"]".
[Error] File: /usr/src/code/src/Appwrite/Database/Database.php
[Error] Line: 235
```

Output
```
JWT:  eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiI2MGJmNGRmYzJjN2Y0Iiwic2Vzc2lvbklkIjoiNjBjOGFkMmI5ZDU3ZSIsImV4cCI6MTYyMzc2NzIyNH0.r0QtMtGMs6P4CWxasR0tHQ0xdJaUA1hSnqzg9AMlnCk
JWT: {'userId': '60bf4dfc2c7f4', 'sessionId': '60c8ad2b9d57e', 'exp': 1623767224}
{'$id': '60bf4dfc2c7f4', 'name': 'Javier', 'registration': 1623150076, 'status': 0, 'passwordUpdate': 1623150076, 'email': 'test@gmail.com', 'emailVerification': True, 'prefs': {}}
```

Same error when permissions are given.
```python
res = storage.create_file(open('image.png', 'rb'), ['user:60bf4dfc2c7f4'], ['user:60bf4dfc2c7f4'])
```

Environment:
- Appwrite 0.8
- Python 3.8
- Appwrite Python SDK 0.3

**Comment by PineappleIOnic** [comment]
Hey Man :wave: 
I've been trying to replicate this issue and I've tried to replicate your code as best as I can but it seems to pass for me. Here is the code I've written. Let me know if there are any major differences between my version and yours.

```python
from appwrite.client import Client;
from appwrite.services.account import Account;
from appwrite.services.storage import Storage;
import jwt;

token = 'token'

token_data = jwt.decode(token, "your-secret-key", algorithms="HS256")
print(f'JWT:  {token}')
print(f'JWT: {token_data}')

# Client
client = Client().set_endpoint('http://localhost/v1').set_project('projectID').set_jwt(token)

# Making sure token is ok
account = Account(client)
print(account.get())

# Creating a new file
storage = Storage(client)
res = storage.create_file(open('image.png', 'rb'))
```

**Comment by JaviBonilla** [comment]
Hi @PineappleIOnic,

Thanks, I don’t see any difference in the code. Are you using Appwrite 0.8 and Python SDK 0.3?

**Comment by PineappleIOnic** [comment]
I am currently using a indev version of appwrite since I was working on something, but I am using the 0.3.0 SDK. I will try and launch a stock appwrite 0.8 instance now and look for any differences :smile:

**Comment by JaviBonilla** [comment]
Yes, I'm creating it from Flutter SKD the `createJWT` account method. The session is open while executing the Python code. Is it working for you?

**Comment by PineappleIOnic** [comment]
Hm, I'm not using the flutter SDK to open the session or generate the JWT. I just call it directly through the API using Postman but that shouldn't cause any differences. Can you try creating the session and generating the JWT Manually using something like Postman? I doubt that's the issue though.

**Comment by PineappleIOnic** [comment]
This issue has been resolved for this person, however we never got to the core of why this happened. If anyone else runs into a issue similar to this one please do not hesitate to reopen this so we can investigate further.
