### ISSUE TITLE
PyPI package error

### ISSUE THREAD

**Issue by Sai-Adarsh** [appwrite/sdk-for-python#5]
PyPI package of appwrite throws error. Tried running
`pip install appwrite` 

> ERROR: Could not find a version that satisfies the requirement appwrite (from versions: none)
> ERROR: No matching distribution found for appwrite

**Comment by sakethramanujam** [comment]
Same error.
I did a quick search on the pypi. seems like below
![image](https://user-images.githubusercontent.com/18083969/66023776-cee69980-e50f-11e9-9a92-a672bbc4aeb3.png)

**Comment by achoudh5** [comment]
I get error 404 when I tried reaching 'https://github.com/appwrite/sdk-for-python/archive/1.0.0.tar.gz'

**Comment by achoudh5** [comment]
`wget  https://github.com/appwrite/sdk-for-python/archive/1.0.0.tar.gz`

--2019-10-06 18:40:32--  `https://github.com/appwrite/sdk-for-python/archive/1.0.0.tar.gz`
Resolving github.com (github.com)... 140.82.113.3
Connecting to github.com (github.com)|140.82.113.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/appwrite/sdk-for-python/tar.gz/1.0.0 [following]
--2019-10-06 18:40:33--  https://codeload.github.com/appwrite/sdk-for-python/tar.gz/1.0.0
Resolving codeload.github.com (codeload.github.com)... 140.82.113.10
Connecting to codeload.github.com (codeload.github.com)|140.82.113.10|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-10-06 18:40:33 ERROR 404: Not Found.

**Comment by batuhantastekin** [comment]
Still the same error

**Comment by eldadfux** [comment]
Hey guys! sorry for the late reply, please note that this project is just a read only project(and still a work in progress) and is actually being auto-generate by our [SDK Generator](https://github.com/appwrite/sdk-generator) project.

Anyway, I haven't registered the project on PyPy yet, I will try to make it happen by the end of the week. Will update here when it's ready.

Thanks for all your feedback.

**Comment by eldadfux** [comment]
Hey guys, just registered our Python SDK beta version in pypi: https://pypi.org/project/appwrite/0.0.1/

Any feedback will be appreciated!

**Comment by PedroCisnerosSantana** [comment]
@Sai-Adarsh could you please try it now and give us feedback?
Thanks. :D
