### ISSUE TITLE
🐛 Bug Report: `Query.orderDesc` and `Query.orderAsc` not working.

### ISSUE THREAD

**Issue by hemangjoshi37a** [appwrite/sdk-for-python#55]
### 👟 Reproduction steps

My code to get doclist :
```dart
    DocumentList doclist = await dbs.listDocuments(
        databaseId: databaseIdTeletest,
        collectionId: this.channelURLtoCollectioIDconverter(),
        queries: [
          Query.limit(limitCountMessages),
          // Query.orderAsc('attribute'),
          Query.orderDesc('messageTimeStr'),
        ]);
```

When I run this without `Query.orderDesc('messageTimeStr')` the this line returns expected results but when I add  `Query.orderDesc('messageTimeStr')` it returns `null`.

### 👍 Expected behavior

Should get ordered doclist.

### 👎 Actual Behavior

not getting doc list.

### 🎲 Appwrite version

Version 0.10.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Everything standard and latest.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@hemangjoshi37a thanks for creating this issue! 🙏🏼 the code snippet you provided doesn't look like it's python...Did you make your issue in the wrong repo?

**Comment by hemangjoshi37a** [comment]
This has been resolved by creating a index for a particular database for a particular attribute. closing now.
