### ISSUE TITLE
📚 Documentation: Updating Readme

### ISSUE THREAD

**Issue by devfinwiz** [appwrite/sdk-for-python#73]
### 💭 Description

'Getting Started Tutorial' link in the readme section is outdated and only results in too many redirects. 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)

**Comment by Kunal-Ladhani** [comment]
I would like to work on this. Can you assign it to me?

**Comment by mschandana16** [comment]
I would like to fix this; can you please assign it to me?

@christyjacob4 @TorstenDittmann @Meldiron

**Comment by Haimantika** [comment]
Hi @devfinwiz thanks for raising this issue. I have made a fix for it
