### ISSUE TITLE
📚 Documentation: Account function being used without importing.

### ISSUE THREAD

**Issue by ayaan-qadri** [appwrite/sdk-for-python#84]
### 💭 Description

The Account function is used in the account's example, but it is not imported there, unlike Client, which is imported. This issue is not specific to one example; rather, all account examples lack the import of the Account module.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)

**Comment by ayaan-qadri** [comment]
(CODE_OF_CONDUCT.md file is not available there)

**Comment by Shriniwas18K** [comment]
can i handle it

**Comment by stnguyen90** [comment]
It looks like when we [added enums](https://github.com/appwrite/sdk-generator/pull/700), we accidentally [deleted that import](https://github.com/appwrite/sdk-generator/commit/c6b568620a09c138ea82fcddc01880ce07cb3f6e#diff-5e6917afab7f018468629a5c5a64c13536c4a85f50e0af6b46304258c49e391c).

I think we just need to add:

```
from {{ spec.title | caseSnake }}.services.{{ service.name | caseSnake }} import {{ service.name | caseUcfirst }}
```

back to the [example template](https://github.com/appwrite/sdk-generator/blob/master/templates/python/docs/example.md.twig).
